### ISSUE TITLE
postproc.lib 已过期

### ISSUE THREAD

**Issue by typetrade** [DoFulangChen/video_implementation#1]
在早期版本的 FFmpeg 中，postproc 库是默认启用的，可以通过命令行选项 -postproc 来应用后处理滤镜。但是自FFmpeg 3.2版本开始，postproc 库被标记为过时（deprecated），不再是默认启用的，而且在最新的 FFmpeg 版本中已经被移除。

现在，建议使用更现代和更强大的滤镜系统，如 libavfilter，来实现视频的后处理和滤波操作。libavfilter 提供了广泛的滤镜和处理器，可以进行更复杂和高级的视频处理。

所以，如果你使用最新版本的 FFmpeg，推荐使用 libavfilter 来进行视频后处理。
————————————————

版权声明：本文为博主原创文章，遵循 CC 4.0 BY 版权协议，转载请附上原文出处链接和本声明。
                        
原文链接：https://blog.csdn.net/weixin_43466192/article/details/131232314

**Comment by typetrade** [comment]
1>C:\video_implementation\include\streamer.cpp(73,16): warning C4018: “<”: 有符号/无符号不匹配
1>C:\video_implementation\include\streamer.cpp(95,16): warning C4018: “<”: 有符号/无符号不匹配
1>C:\video_implementation\include\streamer.cpp(160,26): warning C4244: “初始化”: 从“double”转换到“int64_t”，可能丢失数据
1>C:\video_implementation\include\streamer.cpp(164,53): warning C4244: “=”: 从“double”转换到“int64_t”，可能丢失数据
1>C:\video_implementation\include\streamer.cpp(166,44): warning C4244: “=”: 从“double”转换到“int64_t”，可能丢失数据
1>C:\video_implementation\include\streamer.cpp(176,24): warning C4244: “参数”: 从“int64_t”转换到“unsigned int”，可能丢失数据

建议把警告消除，提升代码质量。

**Comment by DoFulangChen** [comment]
感谢关注和建议，逐步优化~
